trigger:
  - main # Adjust as per your branch strategy

pool:
  vmImage: 'ubuntu-latest' # You can use self hosted agent

steps:
  - task: Maven@3
    displayName: 'Maven Build and Regression Test'
    inputs:
      mavenPomFile: 'pom.xml' # Ensure the correct path to your pom.xml
      goals: 'clean test'
      publishJUnitResults: true # Publish JUnit test results
      testResultsFiles: '**/target/surefire-reports/TEST-*.xml'